---
plugins:
  - import
extends:
  - eslint:recommended
  - plugin:import/recommended

env:
  node: true
  es6: true

parserOptions:
  sourceType: module
  ecmaVersion: 6

rules:
  max-len: [1, 99, 2]
  semi: [2, "never"]
  curly: [2, "multi-line"]
  comma-dangle: [2, always-multiline]
  eqeqeq: [2, "allow-null"]
  no-shadow: 1
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true

  # dog fooding
  import/no-extraneous-dependencies: "error"
  import/unambiguous: "off"

settings:
  import/resolver:
    node:
      paths: [ src ]
