---
extends: eslint:recommended
env:
  node: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 6
rules:
  max-len: [1, 99, 2]
  semi: [2, "never"]
  curly: [2, "multi-line"]
  comma-dangle: [2, always-multiline]
  eqeqeq: [2, "allow-null"]
  no-shadow: 1
