import eslint from 'eslint'
import fileA from './file-a'
import { b } from './file-b'
import { c1, c2 } from './file-c'
import { d } from './file-d'
import { e } from './file-e'
import { h2 } from './file-h'