name: 'Tests: node.js'

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.set-matrix.outputs.requireds }}
      minors: ${{ steps.set-matrix.outputs.optionals }}
    steps:
      - uses: ljharb/actions/node/matrix@main
        id: set-matrix
        with:
          versionsAsRoot: true
          type: majors
          preset: '^18.18.0 || ^20.9.0 || >=21.1.0'

  latest:
    needs: [matrix]
    name: 'majors'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node-version: ${{ fromJson(needs.matrix.outputs.latest) }}
        eslint:
          - 9
          - 8
          - 7
          - 6
          - 5
          - 4
          - 3
          - 2
        include:
          - node-version: 'lts/*'
            os: ubuntu-latest
            eslint: 7
            env:
              TS_PARSER: 4
          - node-version: 'lts/*'
            os: ubuntu-latest
            eslint: 7
            env:
              TS_PARSER: 3
          - node-version: 'lts/*'
            os: ubuntu-latest
            eslint: 7
            env:
              TS_PARSER: 2

    steps:
      - uses: actions/checkout@v4
      - uses: ljharb/actions/node/install@main
        continue-on-error: false
        name: 'nvm install ${{ matrix.node-version }} && npm install, with eslint ${{ matrix.eslint }}'
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: false
          ESLINT_VERSION: ${{ matrix.eslint }}
        with:
          node-version: ${{ matrix.node-version }}
          after_install: npm run copy-metafiles && ./tests/dep-time-travel.sh
          skip-ls-check: true
      - run: npm run pretest
      - run: npm run tests-only
      - uses: codecov/codecov-action@v3.1.5

  node:
    name: 'node 18+'
    needs: [latest]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
